"""Updated artisan

Revision ID: 89b227e7d399
Revises: 2aa98e5b332f
Create Date: 2026-01-20 15:37:40.839415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b227e7d399'
down_revision: Union[str, Sequence[str], None] = '2aa98e5b332f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artisans', sa.Column('fullname', sa.String(), nullable=False))
    op.add_column('artisans', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('artisans', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('artisans', sa.Column('years_of_experience', sa.Float(), nullable=False))
    op.add_column('artisans', sa.Column('nin', sa.Integer(), nullable=False))
    op.add_column('artisans', sa.Column('role', sa.String(), nullable=False))
    op.add_column('artisans', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'artisans', ['nin'])
    op.drop_column('artisans', 'firstname')
    op.drop_column('artisans', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artisans', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('artisans', sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'artisans', type_='unique')
    op.drop_column('artisans', 'is_verified')
    op.drop_column('artisans', 'role')
    op.drop_column('artisans', 'nin')
    op.drop_column('artisans', 'years_of_experience')
    op.drop_column('artisans', 'latitude')
    op.drop_column('artisans', 'longitude')
    op.drop_column('artisans', 'fullname')
    # ### end Alembic commands ###
