"""added  service category 

Revision ID: 9712c4130132
Revises: f6e33580d5de
Create Date: 2026-01-20 23:15:12.567682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9712c4130132'
down_revision: Union[str, Sequence[str], None] = 'f6e33580d5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('service_category', sa.String(), nullable=True))
    op.add_column('users', sa.Column('service_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'service_description')
    op.drop_column('users', 'service_category')
    # ### end Alembic commands ###
