"""Updated the models

Revision ID: e2e99baf094a
Revises: 8017121840ae
Create Date: 2026-01-09 18:28:06.323446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e99baf094a'
down_revision: Union[str, Sequence[str], None] = '8017121840ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.String(), nullable=False))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.drop_column('users', 'location')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###
