"""merge artisans into users

Revision ID: f6e33580d5de
Revises: 89b227e7d399
Create Date: 2026-01-20 22:24:40.096006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e33580d5de'
down_revision: Union[str, Sequence[str], None] = '89b227e7d399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artisan_services', 'artisan_id')
    op.add_column('users', sa.Column('years_of_experience', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('nin', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['nin'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'nin')
    op.drop_column('users', 'years_of_experience')
    op.add_column('artisan_services', sa.Column('artisan_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
