"""add base_price_kobo to artisan_profiles

Revision ID: 27d2f45abf43
Revises: 880d0f3790ac
Create Date: 2025-09-21 13:24:33.035477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d2f45abf43'
down_revision: Union[str, Sequence[str], None] = '880d0f3790ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artisan_profiles', sa.Column('base_price_kobo', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_artisan_profiles_base_price_kobo'), 'artisan_profiles', ['base_price_kobo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artisan_profiles_base_price_kobo'), table_name='artisan_profiles')
    op.drop_column('artisan_profiles', 'base_price_kobo')
    # ### end Alembic commands ###
