"""Make artisan profile fields nullable

Revision ID: 4e5fcca9d92b
Revises: 23e84f3c6681
Create Date: 2025-10-13 11:43:40.524766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e5fcca9d92b'
down_revision: Union[str, Sequence[str], None] = '23e84f3c6681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artisan_profiles', 'service_category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('artisan_profiles', 'years_of_experience',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payout_recipients', 'provider',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payout_recipients', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payout_recipients', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payouts', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payouts', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'service_preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'service_preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('payouts', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('payouts', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'NGN'::character varying"),
               existing_nullable=False)
    op.alter_column('payout_recipients', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('payout_recipients', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'NGN'::character varying"),
               existing_nullable=False)
    op.alter_column('payout_recipients', 'provider',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'paystack'::character varying"),
               existing_nullable=False)
    op.alter_column('artisan_profiles', 'years_of_experience',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artisan_profiles', 'service_category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
